#!/usr/bin/env python3
import sys
import os
import re
import json

def generate(audio_dir, out_h, out_js, effects):
    cc_counter = 40
    midi_map = []  # List of dicts for C output
    ui_effects = [] # List of dicts for JS output

    # Build maps
    for e_idx, base in enumerate(effects):
        header_path = os.path.join(audio_dir, f"{base}.h")
        if not os.path.exists(header_path):
            print(f"Warning: {header_path} not found")
            continue

        with open(header_path, 'r') as f:
            content = f.read()

        struct_match = re.search(r'static struct effect \w+ = \{(.*?)\n\};', content, re.DOTALL)
        if not struct_match:
            print(f"Warning: Could not parse struct for {base}")
            continue

        struct_body = struct_match.group(1)
        name_match = re.search(r'\.name\s*=\s*"([^"]+)"', struct_body)
        short_name_match = re.search(r'\.short_name\s*=\s*"([^"]+)"', struct_body)

        full_name = name_match.group(1) if name_match else base
        short_name = short_name_match.group(1) if short_name_match else base

        pots = []
        pots_match = re.search(r'\.pots\s*=\s*\{(.*?)\n\s*\}', struct_body, re.DOTALL)
        if pots_match:
            pots_body = pots_match.group(1)
            # Find lines like EFFECT_POT("Level", desc_dB, gate_pot0_level, 0)
            pot_lines = re.findall(r'EFFECT_POT\(\s*"([^"]+)"', pots_body)
            for p_idx, pot_label in enumerate(pot_lines):
                pots.append(pot_label)
                # Assign CC for pot
                midi_map.append({
                    "cc": cc_counter,
                    "type": 1, # POT
                    "effect_idx": e_idx,
                    "pot_idx": p_idx
                })
                cc_counter += 1

        # Assign CC for enable
        enable_cc = cc_counter
        midi_map.append({
            "cc": cc_counter,
            "type": 2, # ENABLE
            "effect_idx": e_idx,
            "pot_idx": 0
        })
        cc_counter += 1

        ui_effects.append({
            "id": base,
            "name": full_name,
            "shortName": short_name,
            "enable_cc": enable_cc,
            "pots": pots,
            "pot_ccs": [m["cc"] for m in midi_map if m["effect_idx"] == e_idx and m["type"] == 1]
        })

    # Generate effect_map.h
    with open(out_h, 'w') as f:
        f.write("// Auto-generated by gen_effects.py\n")

        # Includes
        for base in effects:
            f.write(f"#include \"../effects/{base}.h\"\n")

        f.write("\n")

        # Array
        f.write("static struct effect *const effects[] = {\n")
        for base in effects:
            # Most are <base>_effect except EQ which is just EQ
            struct_name = f"{base}_effect" if base != "eq" else "EQ"
            f.write(f"\t&{struct_name},\n")
        f.write("};\n\n")

        # MIDI Map struct
        f.write("struct midi_cc_mapping {\n\tuint8_t type; // 0=none, 1=pot, 2=enable\n\tuint8_t effect_idx;\n\tuint8_t pot_idx;\n};\n\n")
        f.write("static const struct midi_cc_mapping dense_midi_map[128] = {\n")

        map_dict = {m["cc"]: m for m in midi_map}
        for cc in range(128):
            if cc in map_dict:
                m = map_dict[cc]
                f.write(f"\t[{cc}] = {{ .type = {m['type']}, .effect_idx = {m['effect_idx']}, .pot_idx = {m['pot_idx']} }},\n")

        f.write("};\n\n")

        f.write("static const uint8_t effect_enable_to_cc[] = {\n")
        for e_idx in range(len(effects)):
            enables = [m["cc"] for m in midi_map if m["effect_idx"] == e_idx and m["type"] == 2]
            if enables:
                f.write(f"\t[{e_idx}] = {enables[0]},\n")
        f.write("};\n\n")

        f.write("static const uint8_t effect_pot_to_cc[][10] = {\n")
        for e_idx in range(len(effects)):
            f.write(f"\t[{e_idx}] = {{ ")
            for p_idx in range(10):
                pots = [m["cc"] for m in midi_map if m["effect_idx"] == e_idx and m["type"] == 1 and m["pot_idx"] == p_idx]
                if pots:
                    f.write(f"{pots[0]}, ")
                else:
                    f.write("0, ")
            f.write("},\n")
        f.write("};\n\n")

        f.write(f"#define GLOBAL_ENABLE_CC 20\n")
        f.write(f"#define STATE_DUMP_CC 119\n")
        f.write(f"#define EFFECT_COUNT {len(effects)}\n\n")

    # Generate effects.js
    with open(out_js, 'w') as f:
        f.write("// Auto-generated by gen_effects.py\n")
        f.write("const PEDAL_EFFECTS = " + json.dumps(ui_effects, indent=2) + ";\n")
        f.write("const GLOBAL_ENABLE_CC = 20;\n")
        f.write("const STATE_DUMP_CC = 119;\n")

if __name__ == "__main__":
    if len(sys.argv) < 5:
        print("Usage: gen_effects.py <audio_dir> <out_h> <out_js> <effect1> <effect2> ...")
        sys.exit(1)

    generate(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4:])
