#!/usr/bin/env python3
#
# The WS2812B waveform, as a table.
#
# Each of the eight bits in a colour byte becomes four output bits at
# four times the bit rate: '1000' for a zero and '1110' for a one.  At
# the 1.25us WS2812B bit period each output bit is 312.5ns, so:
#
#	zero	312ns high, 938ns low
#	one	938ns high, 312ns low
#
# FOUR, not three, and this is the whole point of the file.  Three bits
# gives a 417ns high for a zero, which is correct for the original
# WS2812B - it asks for 400ns +-150 - and wrong for the WS2812B-2020,
# which asks for **220-380ns** and reads anything longer as a one.  Feed
# a 2020 the three-bit encoding and every bit of every byte comes back
# as a one: all three LEDs sit at 0xffffff and nothing you encode makes
# the slightest difference, because none of it is being read.  That is
# not a subtle failure but it is a confusing one, because the symptom
# looks like a brightness bug rather than a timing one.
#
# The knob test board this came from uses WS2812B-4020, which has the
# older timing and works either way.  Same family, same protocol, and a
# different answer to "how long is a zero".
#
# Four bits also happens to be tidier: eight of them is exactly 32 bits,
# so one colour byte is one whole word with nothing thrown away, and the
# PIO side autopulls at 32 rather than at 24.
#
import sys
from pathlib import Path

def encode(byte):
	word = 0
	for i in range(8):
		bit = (byte >> (7 - i)) & 1
		# '1110' or '1000', most significant bit of the byte first
		word |= (0b1110 if bit else 0b1000) << (28 - 4 * i)
	return word

def generate_table(output_path):
	Path(output_path).parent.mkdir(parents=True, exist_ok=True)

	with open(output_path, 'w') as f:
		f.write("// Generated by scripts/ws2812_table.py - do not edit\n")
		f.write("const uint32_t ws2812_encode[256] = {")

		for i in range(256):
			prefix = "\n\t" if i % 4 == 0 else " "
			f.write(f"{prefix}0x{encode(i):08x},")

		f.write("\n};\n")

if __name__ == "__main__":
	generate_table(sys.argv[1])
