#include "pico.h"

#define CFG_TUSB_RHPORT0_MODE	(OPT_MODE_DEVICE)
#define CFG_TUD_ENABLED		(1)
#define CFG_TUD_AUDIO		(1)

#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SZ_MAX (48 * 4 * 2)
#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SW_BUF_SZ (48 * 4 * 2 * 2)
#define CFG_TUD_AUDIO_ENABLE_EP_IN (1)
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX (4)
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX (32)
