#!/usr/bin/env python3
#
# Embed the radio's image in the pedal's.
#
# Writes a header with the image's length and SHA-256, and the image
# itself pulled in by .incbin, so that pedal.c is still the only
# translation unit.  The radio works out the same hash over its RRAM at
# every boot and reports it in its hello; the pedal rewrites the radio
# when the two differ.
#
# The radio hashes from the start of its image to _flash_used, so this
# refuses an image whose length is not that: the two hashes would never
# agree, and the pedal would rewrite the radio at every boot.
#
# Called as: radio-image.py <zephyr.bin> <zephyr.elf> <nm> <out.h>
#
import hashlib
import subprocess
import sys


def main():
    binfile, elf, nm, out = sys.argv[1:5]

    image = open(binfile, "rb").read()

    res = subprocess.run([nm, elf], capture_output=True, text=True)
    if res.returncode:
        sys.exit(f"radio-image: {nm} failed:\n{res.stderr}")
    used = None
    for line in res.stdout.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[2] == "_flash_used":
            used = int(parts[0], 16)
    if used is None:
        sys.exit(f"radio-image: no _flash_used in {elf}")
    if used != len(image):
        sys.exit(f"radio-image: {binfile} is {len(image)} bytes and "
                 f"_flash_used says {used}")
    if len(image) % 4:
        sys.exit(f"radio-image: {len(image)} bytes is not whole words")

    digest = hashlib.sha256(image).digest()
    hexed = ", ".join(f"0x{b:02x}" for b in digest)

    text = f"""\
// Generated by scripts/radio-image.py from {binfile}
#define NRF54_IMAGE_SIZE	{len(image)}u

static const uint8_t nrf54_image_sha256[32] = {{ {hexed} }};

__asm__(".section .rodata.nrf54_image, \\"a\\"\\n"
	".balign 4\\n"
	"nrf54_image:\\n"
	".incbin \\"{binfile}\\"\\n"
	".previous\\n");
extern const uint8_t nrf54_image[NRF54_IMAGE_SIZE];
"""
    # Only when it changed, so that an unchanged radio rebuilds nothing
    try:
        if open(out).read() == text:
            return
    except FileNotFoundError:
        pass
    open(out, "w").write(text)


main()
